### ISSUE TITLE
Add Pinging steps to project

### ISSUE THREAD

**Issue by MellowFelllow** [MellowFelllow/Network-Troubleshooting#3]
- Add steps to ping 8.8.8.8
- Steps to ping google.com
- Steps to ping Default Gateway
- Steps to ping DNS

**Comment by DeathandSyntaxes** [comment]
Pinging 8.8.8.8 and google.com no issues. 

Receiving errors trying to ping powershell custom objects

**Comment by DeathandSyntaxes** [comment]
Found a method to fix the issues with pinging custom objects, however, it overwrites custom objects section

**Comment by MellowFelllow** [comment]
Worked on issue with pinging pscustomobjects, no success yet

**Comment by MellowFelllow** [comment]
Resolved issue with passing powershell item to a ping for Default Gateway, DNS is next!

**Comment by MellowFelllow** [comment]
Using DNS results may be more complicated as PSobject provides 2x IPV6 addresses and 2x IPV4 addresses, Might be better to use custom commands instead of pulling from the object

**Comment by MellowFelllow** [comment]
Split $DNSServer results into an array with 4 lines, filtered for ipv4 addresses, cleaned filtered results and pinged both, appending each to text file. 

Job Done!
